### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by Caroma97** [NathanReeves/BlueCubeMod#1]
Hi,

first of all, nice project :D
I love the old gamecube controller and it would be awesome if i could use it wireless on my switch.

But i have a problem while compiling the scipt:
[pastebin error log](https://pastebin.com/Bu83mwVP)

My system:
Windows 10 x64
esp32_win32_msys2_environment_and_gcc5_toolchain-20191220 (downloaded from the linked esppressif doc)
esp-idf: master branch from your linked fork

Maybe you know where my mistake is?
This is my first project with the esp, so please be patient. ^^

Greetings
Mario

**Comment by NathanReeves** [comment]
Hey 👋 
Thank you for finding this, I moved some things around and xSemaphore got declared later than it should have. I just pushed a commit to fix this.
Thanks again!
Have fun
-Nathan
