### ISSUE TITLE
Please add an Open Source License

### ISSUE THREAD

**Issue by kyokuheishin** [NathanReeves/BlueCubeMod#3]
Hi, recently I made a Rapid Fire Controller, and I actually used some parts of your codes. And when I want to write a tutorial of that, I noticed that this repo has no Open Source License. Does it mean that you don't want anybody else to modify your code? If not, can you please add any Open Source License? Thank you.

**Comment by NathanReeves** [comment]
Anyone can use the code in their projects 🙂

**Comment by kyokuheishin** [comment]
Thank you!!
