### ISSUE TITLE
building error

### ISSUE THREAD

**Issue by orichienal** [NathanReeves/BlueCubeMod#4]
Hi, 
i want to use this great project, but i cant build it.
The newest esp-idf is not working, i installed an older version (v3.3.2), this will start building.
(because the newest uses idf.py instead of make)

But now i get another failure:
fatal error: esp_hidd_api.h: No such file or directory
compilation terminated.

i cant find "esp_hidd_api.h" on the www.

i dont know what to do.

i hope someone can help me.

I want to use a gamecube controller and experiement with some automated makros....

many thanks
orichienal

**Comment by NathanReeves** [comment]
Hey, 
Sorry the project uses an old fork of the esp-idf here which contains esp_hidd_api:
https://github.com/NathanReeves/esp-idf

**Comment by orichienal** [comment]
Really thank you, i missed it.
maybe you change the second link "Set up the esp-idf environment:", because the newest dont work (no make anymore), i used the last version in 3
https://docs.espressif.com/projects/esp-idf/en/v3.3.1/get-started/index.html

i build a real new msys32 and now i have another failure.

make: *** No rule to make target '/home/orichienal/esp/BlueCubeMod/Firmware/BlueCubeModv2/build/ldgen_libraries', needed by '/home/orichienal/esp/BlueCubeMod/Firmware/BlueCubeModv2/build/esp32/esp32.project.ld'.  Stop.

i searched for it, but i got no luck.

sry, but i want realy to use this thing, i bougth today a controller....

really thank you
orichienal

**Comment by NathanReeves** [comment]
@orichienal 
If you get “no rule to make target” try running make again

**Comment by orichienal** [comment]
i run it several times (more than 5), i changed the com port, i copied to get a shorter path, and know i get this, maybe the compiler version is wrong....


orichienal@PROGSTATION MINGW32 ~/BlueCubeModv2
$ make flash monitor
Toolchain path: /opt/xtensa-esp32-elf/bin/xtensa-esp32-elf-gcc
Toolchain version: crosstool-ng-1.22.0-80-g6c4433a5
Compiler version: 5.2.0
Python requirements from C:/msys32/home/orichienal/esp/esp-idf/requirements.txt are satisfied.

Project is not inside a git repository, will not use 'git describe' to determine PROJECT_VER.
App "BlueCubeModv2" version: 1
make: *** No rule to make target '/home/orichienal/BlueCubeModv2/build/ldgen_libraries', needed by '/home/orichienal/BlueCubeModv2/build/esp32/esp32.project.ld'.  Stop.

**Comment by orichienal** [comment]
which version of toolchain do you use, maybe i need an older one

**Comment by orichienal** [comment]
after hours of searching and testing and a lot of new environment i got a solution

https://github.com/espressif/esp-idf/pull/3420/files
